### ISSUE TITLE
V0.6.1版本bug反馈

### ISSUE THREAD

**Issue by cixiaweiliang** [konatatenshi/zdmobile#1]
1.回复内容切换正序和倒序浏览时，第二页与第一页完全相同，缺少了第二页的回复。但不在帖子内切换则不会出现该bug；
2.求助区的帖子能查看别人回复的bug修复后，自己的回复自己无法看到，也无法看到楼中楼的回复；
3.版本信息里显示“请去商店更新”，而不是“最新版”。

**Comment by cixiaweiliang** [comment]
>

**Comment by konatatenshi** [comment]
2，3这几个都是后台API的问题而不是APP的问题，目前已修复
1无法复现

**Comment by cixiaweiliang** [comment]
> 2，3这几个都是后台API的问题而不是APP的问题，目前已修复 1无法复现

关于第2条，目前仍无法查看。

**Comment by cixiaweiliang** [comment]
> 2，3这几个都是后台API的问题而不是APP的问题，目前已修复 1无法复现

另外，V0.6.1版本虽然能从主页打开私信窗口，但是点击发送无反应，私信发不出去。

提醒页面点击两次当前的分组（全部/系统/帖子/互动）会跳转至该分组下第二页无法回到第一页。只能从其他分组再次切换回来。

**Comment by konatatenshi** [comment]
已经修复完成3，远程判定的
